using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JSBindTool.Core
{
    public static class HeaderUtils
    {
        public static void EmitNotice(CodeBuilder builder)
        {
            builder.Add(new string[] {
                "/// # This file has been generated by the JSBindTool",
                "/// # Don't change this file, otherwise your changes can be lost",
                "/// # by the next time bind tools is running",
                $"/// # Copyright (c) 2017-{DateTime.Now.Year} the rbfx project."
            });
            builder.AddNewLine(1);
        }
    }
}
